spring:
  servlet:
    multipart:
      max-file-size: 1024MB   # 单个文件 1GB
      max-request-size: 1024MB  # 总请求大小 1GB
  application:
    name: offer
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/offer
    username: root
    password: root
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rocklin.offer.model.entity

# springdoc-openapi
springdoc:
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.rocklin.offer.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# pdf图片存储
file:
  upload-dir: data/pdfs/


